name: Continuous Integration

on: [push]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: '3.10'
        environment-file: environment.yml
        activate-environment: fastapi
        auto-activate-base: false
    - name: Install extra dependencies
      shell: bash -l {0}
      run: |
        conda info
        pip install flake8 pytest
    - name: Run Flake8
      shell: bash -l {0}
      run: flake8 . --max-line-length=88 --extend-ignore=E203
    - name: Run PyTest
      shell: bash -l {0}
      run: pytest test_ml.py